version: "3.8"

services:
  k6:
    image: ghcr.io/grafana/xk6-dashboard:0.7.5
    volumes:
      - ./scripts:/scripts
    ports:
      - "5665:5665"
    command: run --out dashboard /scripts/k6-loadtest.js
    network_mode: "host"