version: '3.8'

services:
  wrk-tester:
    container_name: wrk-stress-tester
    build:
      context: .
      dockerfile: Dockerfile.wrk
    volumes:
      - ./logs:/wrk-tests/logs
      - ./scripts/wrk:/wrk-tests/scripts/wrk
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - LEADERBOARD_URL=http://host.docker.internal:8080
    working_dir: /wrk-tests
    tty: true
    stdin_open: true